name: Reusable workflow

on: 
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }}
jobs:
  resusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
    steps:
      - name: Greet someone
        run: echo 'Hello ${{ inputs.who-to-greet }}'
      - id: time
        name: Set current time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
